-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  CASE WHEN 1=1 THEN NULL ELSE NULL END AS TABLE_CATALOG,
  S.SCHEMANAME AS TABLE_SCHEMA,
  T.TABLENAME AS TABLE_NAME,
  V.VIEWDEFINITION AS VIEW_DEFINITION,
  V.CHECKOPTION AS CHECK_OPTION,
  'NO' AS IS_UPDATABLE
FROM
  SYS.SYSVIEWS V,
  SYS.SYSTABLES T,
  SYS.SYSSCHEMAS S
WHERE
  V.TABLEID = T.TABLEID
  AND S.SCHEMAID = T.SCHEMAID
