-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  NULL AS CONSTRAINT_CATALOG,
  CONSTRAINTS.SCHEMA_NAME AS CONSTRAINT_SCHEMA,
  CONSTRAINTS.CONSTRAINT_NAME,
  NULL AS TABLE_CATALOG,
  CONSTRAINTS.SCHEMA_NAME AS TABLE_SCHEMA,
  CONSTRAINTS.TABLE_NAME,
  CASE 
    WHEN CONSTRAINTS.IS_PRIMARY_KEY = 'TRUE' THEN 'PRIMARY KEY'
    WHEN CONSTRAINTS.IS_UNIQUE_KEY  = 'TRUE' THEN 'UNIQUE'
    ELSE 'CHECK'
  END
     AS CONSTRAINT_TYPE,
  'NO' AS IS_DEFERRABLE,
  'NO' AS INITIALLY_DEFERRED
FROM
  SYS.CONSTRAINTS
ORDER BY
  CONSTRAINTS.SCHEMA_NAME,
  CONSTRAINTS.CONSTRAINT_NAME
