-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  NULL AS TRIGGER_CATALOG,
  TRIGGERS.SCHEMA_NAME AS TRIGGER_SCHEMA,
  TRIGGERS.TRIGGER_NAME AS TRIGGER_NAME,
  TRIGGERS.TRIGGER_EVENT AS EVENT_MANIPULATION,
  NULL AS EVENT_OBJECT_CATALOG,
  TRIGGERS.SUBJECT_TABLE_SCHEMA AS EVENT_OBJECT_SCHEMA,
  TRIGGERS.SUBJECT_TABLE_NAME AS EVENT_OBJECT_TABLE,
  0 AS ACTION_ORDER,
  '' AS ACTION_CONDITION,
  TRIGGERS.TRIGGERED_ACTION_LEVEL AS ACTION_ORIENTATION,
  TRIGGERS.TRIGGER_ACTION_TIME AS CONDITION_TIMING,
  '' AS ACTION_STATEMENT,
  NULL AS ACTION_REFERENCE_OLD_TABLE,
  NULL AS ACTION_REFERENCE_NEW_TABLE,
  NULL AS ACTION_REFERENCE_OLD_ROW,
  NULL AS ACTION_REFERENCE_NEW_ROW,
  TRIGGERS.CREATE_TIME AS CREATED,
  TRIGGERS.IS_VALID,
  TRIGGERS.IS_ENABLED,
  TRIGGERS.CREATE_TIME,
  TRIGGERS.TRIGGER_OID,
  TRIGGERS.OWNER_OID,
  TRIGGERS.DEFINITION 
FROM
  SYS.TRIGGERS
