-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  NULL AS TABLE_CATALOG,
  VIEWS.SCHEMA_NAME AS TABLE_SCHEMA,
  VIEWS.VIEW_NAME AS TABLE_NAME,
  VIEWS.DEFINITION AS VIEW_DEFINITION,
  VIEWS.HAS_CHECK_OPTION AS CHECK_OPTION,
  CASE WHEN VIEWS.IS_READ_ONLY = 'N' THEN 'Y' ELSE 'N' END AS IS_UPDATABLE
FROM
  SYS.VIEWS
