name: Database Integration Tests

on:
  workflow_dispatch:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    name: Database Integration Tests
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.7.2
      with:
        java-version: 21
    - id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3

# BUILD DEPENDENCIES
    - id: build-schemacrawler-core
      name: Build SchemaCrawler-Core
      uses: sualeh/build-maven-dependency@v1.0.8
      with:
        repository: schemacrawler/SchemaCrawler-Core
        artifact: us.fatehi:schemacrawler:17.11.3
    - id: build-schemacrawler
      name: Build SchemaCrawler
      uses: sualeh/build-maven-dependency@v1.0.8
      with:
        repository: schemacrawler/SchemaCrawler
        artifact: us.fatehi:schemacrawler-commandline:17.11.3


# RUN DATABASE TESTS
    - id: build-test-databases
      name: Build and run database tests
      env:
        TZ: GMT
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dheavydb \
          clean install \
          org.jacoco:jacoco-maven-plugin:0.8.14:report-aggregate
    - id: gather-expected-results
      name: Gather expected results for failed tests
      if: always()
      shell: bash
      run: |
        # Gather expected results
        echo "Gather expected results"
        # DEBUG
        echo "Current working directory:"
        pwd
        echo "Show expected results directories:"
        find . \
          -type d \
          -name "unit_tests_results_output" \
          -exec echo {} \;
        # Save expected results files
        echo "Zip expected results:"
        .github/scripts/unit-tests-results-output.sh $(realpath .)
    - id: upload-unit-tests-results-output
      name: Upload expected results files
      uses: actions/upload-artifact@v7
      if: always()
      with:
        name: expected-results
        path: ./unit_tests_results_output.zip
        retention-days: 5
        if-no-files-found: ignore

# GET TEST RESULTS
    - id: publish-test-results
      name: Upload results and coverage
      if: contains(github.ref, 'main')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        # Upload results and coverage
        bash <(curl -s https://codecov.io/bash) -t 9b176264-b1dd-412b-83f4-342720a3c7eb
    - id: upload-coverage-test-results
      name: Upload coverage test results
      uses: actions/upload-artifact@v7
      with:
        name: coverage-test-results
        path: ./schemacrawler/target/site/jacoco-aggregate
