name: Integration Tests

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build, test, and publish results
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v0.0.3
    - id: install-packages
      name: Install packages
      run: |
        # Install Graphviz
        sudo apt-get -qq update
        sudo apt-get -q install graphviz
        dot -V

# BUILD AND TEST
    - id: build-test
      name: Build and run integration tests
      env:
        TZ: GMT
      run: |
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dtestcoverage \
          clean install \
          org.jacoco:jacoco-maven-plugin:0.8.5:report-aggregate

# GET TEST RESULTS
    - id: publish-test-results
      name: Upload results and coverage
      if: contains(github.ref, 'master')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -t 9b176264-b1dd-412b-83f4-342720a3c7eb
