name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

# VALIDATE TAGS
    - id: validate-semver
      name: Validate tag against semantic versioning
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        SEMVER_PATTERN="^refs/tags/v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$"
        if [[ ! $GITHUB_REF =~ $SEMVER_PATTERN ]]
          then
            echo "Tag $GITHUB_REF does not follow semantic versioning"
            exit 1
          fi

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.6.1
      with:
        java-version: 21

# BUILD FOR DISTRIBUTION
    - id: build
      name: Build and test for distribution
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          clean install

# CREATE GITHUB RELEASE
    - id: create-release
      name: Create GitHub release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          SchemaCrawler ${{ github.event.release.tag_name }} release at last commit ${{ github.sha }}
          See the change history at https://www.schemacrawler.com/changes-report.html
        generate_release_notes: true

# PUBLISH TO CENTRAL REPOSITORY
    - id: publish-to-central
      name: Publish to Central Repository
      if: startsWith(github.ref, 'refs/tags/')
      env:
        MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      shell: bash
      run: |
        # Publish to Central Repository
        export GPG_TTY=$(tty)
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dmaven.javadoc.skip=false \
          -Dskip.signing.artifacts=false \
          clean deploy
